import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:relink_mobile/crypto/demo_key.dart';
import 'package:relink_mobile/crypto/medical_crypto.dart';

void main() {
  final key = Uint8List.fromList(
      base64Decode('AvhVqE/lK/Jv/o5kalpkYjBKHJSxolRrw9j52m1qqCQ='));
  final crypto = MedicalCrypto();

  group('AES-256-GCM round-trip', () {
    test('encrypt -> decrypt restores the sensitive fields', () async {
      final sensitive = {
        'conditions': 'Asthma, Type-2 Diabetes',
        'medications': 'Salbutamol inhaler, Metformin 500mg',
        'insurance_provider': 'Star Health',
        'insurance_policy_number': 'P/161130/01/2024/000001',
      };
      final envelope = await crypto.encryptBytes(
        utf8.encode(jsonEncode(sensitive)),
        key,
      );
      final restored = await crypto.decryptFields(envelope, key);
      expect(restored, sensitive);
    });

    test('envelope layout is base64([12B nonce][ct][16B tag])', () async {
      final envelope =
          await crypto.encryptBytes(utf8.encode('{"a":"b"}'), key);
      final combined = base64Decode(envelope);
      // nonce (12) + ciphertext (9) + tag (16)
      expect(combined.length, 12 + 9 + 16);
    });

    test('decrypt with wrong key is rejected', () async {
      final envelope =
          await crypto.encryptBytes(utf8.encode('{"a":"b"}'), key);
      final wrongKey = Uint8List.fromList(List.filled(32, 7));
      expect(
        () => crypto.decryptFields(envelope, wrongKey),
        throwsA(isA<MedicalCryptoException>()),
      );
    });

    test('tampered ciphertext fails authentication', () async {
      final envelope =
          await crypto.encryptBytes(utf8.encode('{"a":"b"}'), key);
      final combined = base64Decode(envelope);
      combined[combined.length - 1] ^= 0xFF; // flip a bit in the tag
      expect(
        () => crypto.decryptFields(base64Encode(combined), key),
        throwsA(isA<MedicalCryptoException>()),
      );
    });

    test('malformed base64 is rejected', () {
      expect(
        () => crypto.decryptFields('!!! not base64 !!!', key),
        throwsA(isA<MedicalCryptoException>()),
      );
    });
  });

  group('cross-language golden vector', () {
    // Generated by tool/gen_golden_vector.dart; the backend test decrypts the
    // SAME ciphertext in Python. This side proves Dart reproduces it exactly.
    test('Dart reproduces the shared vector deterministically', () async {
      final nonce = base64Decode('MTIzNDU2Nzg5MGFi'); // fixed test nonce
      final sensitive = {
        'conditions': 'Asthma, Type-2 Diabetes',
        'medications': 'Salbutamol inhaler, Metformin 500mg',
        'insurance_provider': 'Star Health',
        'insurance_policy_number': 'P/161130/01/2024/000001',
      };
      final envelope = await crypto.encryptBytes(
        utf8.encode(jsonEncode(sensitive)),
        key,
        nonce: nonce,
      );
      const expected =
          'MTIzNDU2Nzg5MGFiih5UBr/B5OwTvwfWmewx7HRSEbpkeLxM53YC2EzAStlJf10/IvzWEybVb0gXMIKAkfXLVLMxN4xb5IDEDozPAFyHv9Oc0c5VrYVDENFCMi04Mz8YoEVP8I1Ln5KFK58vwDWzQGaK/+6KM3FnNDTbBgjwHsg54BfJqcwCR2ZXpcuv79WVDnv/BptMNuGo1XW3wjc1c4mPeQVwCgiZPfkTlMkiISJPaZHo7uAuntYY3aR5qSVcV5kOueaWjwI4XAtD1zlO';
      expect(envelope, expected);

      // And it round-trips back.
      final restored = await crypto.decryptFields(envelope, key);
      expect(restored, sensitive);
    });
  });

  group('demo key loading', () {
    test('no --dart-define supplied in test => key unavailable', () {
      // Tests run without the dart-define, so this is the safety fallback path.
      expect(MedicalDemoKey.isAvailable, isFalse);
      expect(MedicalDemoKey.load(), isNull);
    });

    test('encryptFields returns null when no key is configured', () async {
      // Must never throw — SOS falls back to unencrypted.
      final result = await MedicalCrypto()
          .encryptFields({'conditions': 'x'});
      expect(result, isNull);
    });
  });
}
