"""ML Flood & Landslide Susceptibility Router.

Serves region outputs generated by the ML pipeline (risk polygons, historical
disaster points, point susceptibility lookups, and model metadata).

Terminology discipline (per master plan and ML README): All wording surfaces
"potential hazard-prone region" / "susceptibility model", never "active detection".
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Query

from app.config import get_settings

router = APIRouter(prefix="/api/ml", tags=["ml_risk"])

DISCLAIMER = (
    "Susceptibility indicates terrain and rainfall predisposition to flooding or "
    "landslides; it is a predictive model, not a sensor detection of an active event."
)


def _get_region_dir(region: str) -> Path:
    settings = get_settings()
    base_dir = settings.ml_outputs_path()
    
    # Try exact match, title case, or lowercase match
    candidates = [
        base_dir / region,
        base_dir / region.capitalize(),
        base_dir / region.title(),
        base_dir / region.lower(),
    ]
    for c in candidates:
        if c.is_dir():
            return c
    raise HTTPException(
        status_code=404,
        detail=f"Region '{region}' not found in ML outputs ({base_dir}).",
    )


def _point_in_polygon(x: float, y: float, poly_coords: list[list[float]]) -> bool:
    """Ray-casting algorithm to determine if point (x=lng, y=lat) is in a polygon ring."""
    inside = False
    n = len(poly_coords)
    if n < 3:
        return False
    p1x, p1y = poly_coords[0]
    for i in range(1, n + 1):
        p2x, p2y = poly_coords[i % n]
        if y > min(p1y, p2y):
            if y <= max(p1y, p2y):
                if x <= max(p1x, p2x):
                    if p1y != p2y:
                        xinters = (y - p1y) * (p2x - p1x) / (p2y - p1y) + p1x
                    if p1x == p2x or x <= xinters:
                        inside = not inside
        p1x, p1y = p2x, p2y
    return inside


def _point_in_feature_geometry(lng: float, lat: float, geom: dict[str, Any]) -> bool:
    gtype = geom.get("type")
    coords = geom.get("coordinates", [])
    if gtype == "Polygon":
        if not coords or not _point_in_polygon(lng, lat, coords[0]):
            return False
        # If in outer ring, ensure it is NOT in any hole
        for hole in coords[1:]:
            if _point_in_polygon(lng, lat, hole):
                return False
        return True
    elif gtype == "MultiPolygon":
        for poly in coords:
            if poly and _point_in_polygon(lng, lat, poly[0]):
                in_hole = any(_point_in_polygon(lng, lat, h) for h in poly[1:])
                if not in_hole:
                    return True
    return False


@router.get("/risk-regions")
def get_risk_regions(
    region: str = Query("kerala", description="Region name, e.g. kerala or idukki"),
    bbox: str | None = Query(
        default=None,
        description="Optional bounding box 'min_lng,min_lat,max_lng,max_lat' to filter visible polygons",
    ),
):
    """Returns High and Very High risk polygons as a GeoJSON FeatureCollection."""
    reg_dir = _get_region_dir(region)
    geojson_path = reg_dir / "risk_regions.geojson"
    if not geojson_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"risk_regions.geojson not found for region '{region}'.",
        )

    content = json.loads(geojson_path.read_text(encoding="utf-8"))

    if not bbox:
        return content

    # Viewport Bounding Box Filter
    try:
        parts = [float(v.strip()) for v in bbox.split(",")]
        if len(parts) != 4:
            raise ValueError()
        min_x, min_y, max_x, max_y = parts
    except ValueError:
        raise HTTPException(
            status_code=400,
            detail="bbox must be 'min_lng,min_lat,max_lng,max_lat' in float numbers.",
        )

    filtered_features = []
    for f in content.get("features", []):
        geom = f.get("geometry", {})
        coords = geom.get("coordinates", [])
        gtype = geom.get("type")

        # Quick bbox check on outer ring points
        rings = []
        if gtype == "Polygon" and coords:
            rings = [coords[0]]
        elif gtype == "MultiPolygon" and coords:
            rings = [p[0] for p in coords if p]

        overlaps = False
        for ring in rings:
            xs = [pt[0] for pt in ring]
            ys = [pt[1] for pt in ring]
            if xs and ys:
                if (
                    min(xs) <= max_x
                    and max(xs) >= min_x
                    and min(ys) <= max_y
                    and max(ys) >= min_y
                ):
                    overlaps = True
                    break

        if overlaps:
            filtered_features.append(f)

    return {
        "type": "FeatureCollection",
        "name": content.get("name", "risk_regions_filtered"),
        "crs": content.get("crs"),
        "features": filtered_features,
    }


@router.get("/historical-landslides")
def get_historical_landslides(
    region: str = Query("kerala", description="Region name, e.g. kerala or idukki"),
):
    """Returns historical event point inventory as GeoJSON."""
    reg_dir = _get_region_dir(region)
    path = reg_dir / "historical_landslides.geojson"
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"historical_landslides.geojson not found for region '{region}'.",
        )
    return json.loads(path.read_text(encoding="utf-8"))


@router.get("/point-risk")
def get_point_risk(
    lat: float = Query(..., ge=-90, le=90),
    lng: float = Query(..., ge=-180, le=180),
    region: str = Query("kerala"),
):
    """Tests if GPS coordinates fall into a modeled high-susceptibility zone."""
    reg_dir = _get_region_dir(region)
    geojson_path = reg_dir / "risk_regions.geojson"
    if not geojson_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"risk_regions.geojson not found for region '{region}'.",
        )

    data = json.loads(geojson_path.read_text(encoding="utf-8"))
    for f in data.get("features", []):
        geom = f.get("geometry", {})
        if _point_in_feature_geometry(lng, lat, geom):
            props = f.get("properties", {})
            return {
                "in_risk_zone": True,
                "lat": lat,
                "lng": lng,
                "risk_class": props.get("risk_class", 4),
                "risk_name": props.get("risk_name", "High"),
                "prob_mean": props.get("prob_mean"),
                "prob_max": props.get("prob_max"),
                "area_km2": props.get("area_km2"),
                "message": f"Location is inside modeled {props.get('risk_name', 'High')} hazard susceptibility zone.",
                "disclaimer": DISCLAIMER,
            }

    return {
        "in_risk_zone": False,
        "lat": lat,
        "lng": lng,
        "risk_class": 2,
        "risk_name": "Low / Moderate",
        "message": "Location is outside designated high-risk polygons.",
        "disclaimer": DISCLAIMER,
    }


@router.get("/metadata")
def get_ml_metadata(
    region: str = Query("kerala"),
):
    """Returns model training performance, feature layers, and source citations."""
    reg_dir = _get_region_dir(region)
    meta_file = reg_dir / "source_metadata.json"
    metrics_file = reg_dir / "model_metrics.json"

    sources = json.loads(meta_file.read_text(encoding="utf-8")) if meta_file.exists() else {}
    metrics = json.loads(metrics_file.read_text(encoding="utf-8")) if metrics_file.exists() else None

    return {
        "region": region,
        "model_metrics": metrics,
        "sources": sources,
        "rainfall_resolution_note": (
            "Native IMD rainfall is ~0.25 deg (~25 km); resampling to 30 m grid "
            "interpolates the coarse field and does not create 30 m ground accuracy."
        ),
        "disclaimer": DISCLAIMER,
    }
