"""Break-glass medical decrypt endpoint tests (phase_3.md §8/§10).

Proves the cross-language contract: a ciphertext produced on-device by Dart's
`AesGcm.with256bits` (SecretBox.concatenation layout) decrypts correctly in
Python. The golden vector JSON is generated by mobile/tool/gen_golden_vector.dart.
"""

import base64
import json
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from app.services.medical_crypto import decrypt_medical

GOLDEN = json.loads((Path(__file__).parent / "golden_vector.json").read_text())
KEY_B64 = GOLDEN["key_base64"]
CIPHERTEXT_B64 = GOLDEN["ciphertext_base64"]
EXPECTED = GOLDEN["expected"]


@pytest.fixture(autouse=True)
def _key_env(monkeypatch):
    # Point the service at the golden-vector key for every test in this module.
    monkeypatch.setenv("MEDICAL_CARD_DEMO_KEY", KEY_B64)


# --- pure service-level cross-language check ---


def test_python_decrypts_dart_golden_vector():
    assert decrypt_medical(CIPHERTEXT_B64) == EXPECTED


def test_wrong_key_rejected(monkeypatch):
    other = base64.b64encode(b"\x07" * 32).decode()
    monkeypatch.setenv("MEDICAL_CARD_DEMO_KEY", other)
    from app.services.medical_crypto import MedicalDecryptError

    with pytest.raises(MedicalDecryptError):
        decrypt_medical(CIPHERTEXT_B64)


def test_malformed_base64_rejected():
    from app.services.medical_crypto import MedicalDecryptError

    with pytest.raises(MedicalDecryptError):
        decrypt_medical("!!! not base64 !!!")


def test_too_short_payload_rejected():
    from app.services.medical_crypto import MedicalDecryptError

    with pytest.raises(MedicalDecryptError):
        decrypt_medical(base64.b64encode(b"short").decode())


# --- endpoint-level ---


def _post(client, **overrides):
    body = {"ciphertext": CIPHERTEXT_B64, "demo_pass": "relink-demo"}
    body.update(overrides)
    return client.post("/medical/decrypt", json=body)


def test_endpoint_decrypts_golden_vector(client):
    r = _post(client)
    assert r.status_code == 200
    assert r.json()["status"] == "success"
    assert r.json()["decrypted_data"] == EXPECTED


def test_endpoint_wrong_passphrase_401(client):
    r = _post(client, demo_pass="wrong-pass")
    assert r.status_code == 401


def test_endpoint_bad_ciphertext_422(client):
    r = _post(client, ciphertext="!!! not base64 !!!")
    assert r.status_code == 422


def test_endpoint_roundtrip_fresh_ciphertext(client):
    """A ciphertext encrypted fresh in Python also round-trips through the endpoint."""
    key = base64.b64decode(KEY_B64)
    nonce = b"\x01" * 12
    payload = {"conditions": "Hypertension", "medications": "Amlodipine 5mg"}
    ct = AESGCM(key).encrypt(nonce, json.dumps(payload).encode(), None)
    envelope = base64.b64encode(nonce + ct).decode()
    r = _post(client, ciphertext=envelope)
    assert r.status_code == 200
    assert r.json()["decrypted_data"] == payload
